export default {
    TEXT: {
        ATTENDANCE_TITLE: 'LIVE ATTENDANCE',
        SUCCESS: 'success',
        ERROR: 'error',
        ON_REGISTER_BIOMETRIC: 'Mendaftarkan ID Biometrik Perangkat',
        FAILED_CONFIG: 'Konfigurasi gagal',
        ERROR_GET_BIOMETRIC_ID: 'Terjadi masalah saat mengambil ID Biomentrik perangkat',
        REGIS_BIOMETRIC_SUCCESS: 'Konfigurasi Berhasil',
        REGIS_BIOMETRIC_FAILED: 'Konfigurasi Gagal',
        INFO_DESCRIPTION: {
            INFO_1: 'Pastikan perangkat anda mendukung biometrik sidik jari',
            INFO_2: 'Pastikan sidik jari anda sudah di konfigurasi di pengaturan perangkat',
            INFO_3: 'Pastikan ID Biometrik perangkat anda berhasil di daftarkan ke server',
            INFO_4: 'Pastikan login dengan akun anda sendiri di saat pendaftaran ID Biometrik perangkat',
        },
        MAPS_LOADING: 'Memuat Peta',
        SHOULD_LOADING_MAPS: 'Sedang Memuat Peta',
        BIOMETRIC_NO_SUPPORT: 'Biometrik sidik jari tidak support untuk perangkat ini',
        TOUCH_ICON: 'Sentuh ikon sidik jari untuk memulai absen',
        DELETE_DEVICE_KEY: 'HAPUS KUNCI PERANGKAT',
        CLOCK_IN: 'Absen Masuk',
        CLOCK_OUT: 'Absen Keluar',
        VALIDATE_FINGERPRINT: 'Validasi Sidik Jari',
        HIT_BIOMETRIC_SUCCESS: 'Absen Berhasil',
        HIT_BIOMETRIC_FAILED: 'Absen Gagal',
        HIT_BIOMETRIC_ERROR: 'Terjadi masalah saat absen',
    },
};
